from .overview import render_project_overview
from .quick_actions import render_quick_actions
from .dataset_summary import render_dataset_summary
from .workflow import render_workflow_progress
from .pipeline import render_pipeline_summary
from .recent_activity import render_recent_activity